### PR TITLE
Add support for overriding default settings

### PR DESCRIPTION
**Pull request by jespr**
This is an attempt at fixing issue #3

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work on this! 👍 

If I read this correctly, that this PR allows for Ray to be configured from the outside. 

What seems to be missing is the part where a config file is being read from disk (like in the PHP package). Is this something you could add?

**Comment by jespr** [comment]
We could go that route too. But typically gems are configured through initializers over a config file, at least in rails - could be that I’m not too aware of how you’re generally doing this type of stuff in Ruby and therefore went the rails route

**Comment by jespr** [comment]
I should’ve RTFM before doing this :) let me take another stab at it

**Comment by acetinick** [comment]
As per standards in rails , the PR is correct in using initialisers rather than config files. This is how all gems are configured.

**Comment by freekmurze** [comment]
I'd welcome a PR from anyone to help on this. The intention here is to let the package read a config file, so people can configure stuff in the file. PHP equivalent docs: https://spatie.be/docs/ray/v1/configuration/general

This would fix #14

**Comment by acetinick** [comment]
It should not be config file, no Rails gems do this.  It should be initializer like how this is implemented.

**Comment by freekmurze** [comment]
Am I correct in presuming that in order to configure Ray, you would have to make code changes in your own project to define settings? How would you go about developers on the same project wanting to use different settings?

**Comment by jespr** [comment]
Sorry. Had a family emergency, that’s why I stalled on this. I see two ways of doing this, this initializer way with ray.rb in .gitignore. Or we can add a .ray file (gitignore again) to the project root dir or in your home directory - so those would be the two locations it searches for the file. We could do the recursive search up through directories as well, just seems a bit overkill based on what other gems do

**Comment by freekmurze** [comment]
> Had a family emergency, that’s why I stalled on this.

There are no deadlines in open source, so no need to apologise. Hope everything is ok with you and your family.

> Or we can add a .ray file (gitignore again) to the project root dir or in your home directory - so those would be the two locations it searches for the file. We could do the recursive search up through directories as well, just seems a bit overkill based on what other gems do

I'm in favour of using a .ray file and search up through the directory. Most PHP packages don't do it this way. But the Ray one does (and I believe the ruby-ray should do this as well) for these reasons:

- this allows you to use one config file in a parent directory to configure all your projects at once
- this configuration is developer specific, different developers on the same project, might want to use different preferences. So it makes sense, not include the configuration values in a default ruby config file.

Feel free to reason against having a config file, but I only see upsides.

**Pull request closed without merging**
